### ISSUE TITLE
How do I add my Wallet to this?

### ISSUE THREAD

**Issue by theshabobo** [jnbarlow/monero-nodeboard#1]
How do I add my Wallet to this?

**Comment by jnbarlow** [comment]
@theshabobo you have to open the Monero client in advanced mode.  From there, go to `Settings -> Node` and pick `Remote Node` (go ahead and stop the local daemon).  Click the + on `Add Remote Node`, then add the ip and port of where you're running the container.

![image](https://github.com/jnbarlow/monero-nodeboard/assets/1322371/fe53c2e3-8a8f-4578-9c1e-f0eadf82a067)
![image](https://github.com/jnbarlow/monero-nodeboard/assets/1322371/cf6a7895-4521-4b9d-8e83-50d230ea4218)
![image](https://github.com/jnbarlow/monero-nodeboard/assets/1322371/8936cfb7-02af-4927-9ddc-016854beac22)

I marked mine as a Trusted Daemon as well.
