### ISSUE TITLE
Can't connect to monero-nodeboard locally

### ISSUE THREAD

**Issue by rgreco87** [jnbarlow/monero-nodeboard#11]
Hi there,

I just finished to setting up your container, it's up and running.
But I can't get it to work in Monero official client running on Linux VM.

I tried to add the remote node using internal IP address 192.168.x.x and 18081 port, but it doesn't work.
I tried the same with http://192.168.x.x and 18081 port, but it doesn't work.
I tried to add the remote node using my WAN IP address and port 18089 enabled in my router's Port Forwarding section by selecting TCP-UDP and 18089 as both external and internal port and it connected.

Anyway I don't want to make my node public, so I need to connect from Monero official client running on Linux VM from INSIDE my network, not outside.

Can you please help me?
Thanks

**Comment by jnbarlow** [comment]
@rgreco87 it sounds like a docker networking issue...  The only main difference between 18089 and 18081 is that the 18081 has all the remoterpc stuff enabled (so you can get stats from your node.  That said, you should be able to connect to either inside your network.

One other thing to keep in mind is that parts of the node won't stand up until it's done syncing from the network which can take quite a while (which is probably why 18081 didn't work initially.   Watch the logs / output of the container to see when it's done syncing.... it's got to grab multiple GB of data.

Have you tried connecting to the dashboard yet?

**Comment by rgreco87** [comment]
> Have you tried connecting to the dashboard yet?

Hello @jnbarlow, sure, I was monitoring sync status and it reported "Busy Syncing: Nope, up to date.".

Anyway, now it seems to work.
I have another question: I set "Public_Node" to "false" and then I reboot the container, but I can still see inbound connections.
Is that normal?

Thanks

**Comment by jnbarlow** [comment]
@rgreco87 I'm glad you got it going.

setting public node to false should prevent the restricted node on port 18089 from coming up (and from you broadcasting to the network that you're available). Additionally, not opening up 18089 or 18081 on your firewall will ensure that no outside connections can get to you.

There might be some two way syncing shenanigans that happens over the sync protocol, but I don't know enough about the monero client to speak intelligently on that one.

if it's configured correctly, you should see something like this in the logs at startup:
```
---------------------------------false---------------------------
------------------------------------------------------------
```

if not then it didn't see the public_node flag..  Be sure to define that as PUBLIC_NODE in the environment (case matters)
