### ISSUE TITLE
flag

### ISSUE THREAD

**Issue by isdedina** [jnbarlow/monero-nodeboard#15]
Hello, 
is it possible to add flag --zmq-pub tcp://0.0.0.0:18083, or how to add it while updating container?
Thank you,
Ivo

**Comment by jnbarlow** [comment]
@isdedina you should be able to just add that into the `bitmonero.conf` config file mounted at `/config` .   In unraid, this is in the `/appdata/monero-nodeboard` folder

```
zmq-pub=tcp://0.0.0.0:18083
```

**Comment by isdedina** [comment]
Thank you, it works.
Ivo
