### ISSUE TITLE
Geolocation Map on Dashboard

### ISSUE THREAD

**Issue by AgentHarm** [jnbarlow/monero-nodeboard#2]
Hey love the dashboard, I was thinking it would be neat if it also had a geolocation map of the WAN IP's that are displayed

**Comment by jnbarlow** [comment]
Good idea!  I added it to the dashboard's project: https://github.com/jnbarlow/monero-dashboard/issues/9

I'm glad you're enjoying the project! It was a fun exercise in 1) getting the blockchain off my desktop, and 2) giving back to Unraid :)
