### ISSUE TITLE
Add Conversion Rates

### ISSUE THREAD

**Issue by AgentHarm** [jnbarlow/monero-nodeboard#3]
Just looking at your other project monero-dashboard, it has an [xmr ticker in this image](https://github.com/jnbarlow/monero-dashboard/blob/main/readme_assets/screenshot.png) 

Is it possible to get that on the monero-nodeboard? [Nodeboard Screenshot from your page](https://private-user-images.githubusercontent.com/1322371/289389243-b58736bd-4386-498e-a1e6-821e2dbf7634.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyMjk2NDcsIm5iZiI6MTcwMzIyOTM0NywicGF0aCI6Ii8xMzIyMzcxLzI4OTM4OTI0My1iNTg3MzZiZC00Mzg2LTQ5OGUtYTFlNi04MjFlMmRiZjc2MzQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjJUMDcxNTQ3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTRiNmFjNzU4NjM5NTJkMTk5NzdlNGZhM2EwZWIzNDQzN2NlYTQ0NTZkMmQxMWRiMThmYTRmZThlN2Q4YTI3MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.1n_BTf4NLAvMtzSYKynLLZtQtUMck3v50IMv0e_OCrg)

**Comment by jnbarlow** [comment]
Ope ... I didn't expose that as a configurable point did I? :)  Great catch.  Yeah, I'll see about getting that done for you :)

**Comment by jnbarlow** [comment]
@AgentHarm If you're using the container directly, you just need to set up an ENV var of `TICKER` set to true to show it.  I've updated the unraid template and am pushing a new build now... I'm just not sure if the template auto-updates or if I need to ask the maintainers of the Community Applications to re-import it.

**Comment by jnbarlow** [comment]
@AgentHarm in the meantime, you can do this in your docker config on unraid to make it show up: 
![image](https://github.com/jnbarlow/monero-nodeboard/assets/1322371/bb2a83c0-52f0-4d32-83ff-83d365b77056)

**Comment by AgentHarm** [comment]
tried forcing the container to update, didn't appear, but adding that manually worked, thanks!
