### ISSUE TITLE
Upgrading to 0.18.3.1

### ISSUE THREAD

**Issue by samssausages** [jnbarlow/monero-nodeboard#4]
Hi, enjoying the docker container that you created, thanks!  But I'm noticing it hasn't been updated to the latest release from back in Oct.  Do you plan on upgrading to the newer version?  If not, do you have the docker file available?  I was going to build from scratch but looks like you already did most of the heavy lifting!

Cheers,

Sam

**Comment by samssausages** [comment]
Oops, looks like I see a dockerfile in there, not sure why I didn't see it.  I'll give that a look when I have time.

**Comment by jnbarlow** [comment]
@samssausages I've been keeping my eye on things for major releases that effect the block chain. If it's worth jumping these minor releases for the cli version, then I'll get that updated. Thanks for the heads up.

**Comment by jnbarlow** [comment]
@samssausages image updated.  Pull an update in Unraid and you'll get the new goodness :)

**Comment by samssausages** [comment]
Cool thanks!  I'll check it out when I get home tonight!

**Comment by samssausages** [comment]
Seems to be working, I'll report back if I have any issues.  Thank you!
