### ISSUE TITLE
Upgrading to 0.18.3.3

### ISSUE THREAD

**Issue by AgentHarm** [jnbarlow/monero-nodeboard#8]
Hey not sure if it's related, but my wallet which is 0.18.3.3 won't sync past a certain point with my node that is currently 0.18.3.1, not sure if that's related or not. Though when I connect it to another 3rd party trusted server it fully syncs no problem
Is there a command I can run to get it to 0.18.3.3? or should I just wait until there's an update on unraid?

**Comment by jnbarlow** [comment]
Ahh crap. It might be. Point releases usually don't cause breaking changes like that, but they could have added something that has to be there. I'll work on getting another image out tomorrow (I need to add some debugging stuff for another bug anyhow).

I need to set up an alert or something to let me know when new releases are available.

**Comment by AgentHarm** [comment]
Thanks for looking into, no pressure :) love just being able to easily host a node

**Comment by jnbarlow** [comment]
@AgentHarm Monero updated. It took a hot minute to come back up after the container started... it was stuck reading the file, but after about 30 seconds or so the RPC server came up.

**Comment by samssausages** [comment]
> Monero updated. 

Thanks for the update, I'll test it out this weekend!

**Comment by samssausages** [comment]
@jnbarlow I have been running it a few days now, works great.  Thanks!
